# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dump_list',
            new_name='Dump',
        ),
    ]
