# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddos', '0002_auto_20160308_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dump',
            old_name='analysis_id',
            new_name='analysis',
        ),
    ]
